[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PyMSM"
authors = [{name = "Hagai Rossman, Ayya Kehset", email = "hagairossman@gmail.com"}]
dynamic = ["version", "description"]
